- name: Create Database Objects
  hosts: localhost
  vars:
    username:         scott
    password:         tiger
    dbhost:           cs-greybox-mvp-dbcs-1
    service_name:     pdb1.588919103.oraclecloud.internal
    table_name:       api_test_t
    tab_col_list:     >-
                      seq_no      number,
                      insert_date date,
                      message     varchar2(1000)                      
    seq_name:         api_test_s
    create_table:     >-
                      create table {{ table_name }} 
                        (
                        {{ tab_col_list }}
                        )
    create_seq:       >-
                      create sequence {{ sequence_name }}
    
  tasks:
    - name: create table, if it doesn't exist
      oracle_sql: 
        username:     "{{ username }}" 
        password:     "{{ password }}" 
        host:         "{{ dbhost }}" 
        service_name: "{{ service_name }}" 
        sql:          >
                      DECLARE
                        t_count INTEGER;
                        v_sql   VARCHAR2(1000) := '{{ create_table }}';
                        
                      BEGIN
                        SELECT COUNT(*)
                        INTO   t_count
                        FROM   user_tables
                        WHERE  UPPER(table_name) = UPPER('{{ table_name }}');
                        
                        IF t_count = 0 THEN
                          EXECUTE IMMEDIATE v_sql;
                        END IF;
                      END;
                      
    - name: create sequence, if it doesn't exist
      oracle_sql: 
        username:     "{{ username }}" 
        password:     "{{ password }}" 
        host:         "{{ dbhost }}" 
        service_name: "{{ service_name }}" 
        sql:          >
                      DECLARE
                        t_count INTEGER;
                        v_sql   VARCHAR2(1000) := '{{ create_seq }}';
                        
                      BEGIN
                        SELECT COUNT(*)
                        INTO   t_count
                        FROM   user_sequences
                        WHERE  UPPER(sequence_name) = UPPER('{{ seq_name }}');
                        
                        IF t_count = 0 THEN
                          EXECUTE IMMEDIATE v_sql;
                        END IF;
                      END;
