- name: Create Database Objects
  hosts: localhost
  vars:
  tasks:
    - name: drop sequence
      oracle_sql: 
        username:     scott 
        password:     tiger 
        host:         cs-greybox-mvp-dbcs-1 
        port:         1521 
        service_name: pdb1.588919103.oraclecloud.internal 
        sql:          >
                      DECLARE
                        does_not_exist   EXCEPTION;
                        PRAGMA EXCEPTION_INIT (does_not_exist, -2289);
                      BEGIN
                        EXECUTE IMMEDIATE 'drop sequence api_test_s';
                      EXCEPTION
                        WHEN does_not_exist
                        THEN
                          NULL;
                      END;
                      /
