- name: Create Database Objects
  hosts: localhost
  vars:
  tasks:
    - name: create sequence
      oracle_sql: 
        username:     scott 
        password:     tiger 
        host:         cs-greybox-mvp-dbcs-1 
        port:         1521 
        service_name: pdb1.588919103.oraclecloud.internal 
        sql:          'select * 
                       from dual'
